### ISSUE TITLE
beta 14

### ISSUE THREAD

**Issue by ghost** [FriendsOfFlarum/moderator-notes#13]
beta 14 installed. The site crashed when I installed the extension. gave this error.

```
Next Symfony\Component\Translation\Exception\InvalidResourceException: The file "/var/www/html/flarum/vendor/composer/../tolgaaaltas/flarum-ext-turkish/locale/fof-moderator-notes.yml" does not contain valid YAML: Unexpected characters near " taklit etmek için FoF Impersonate kullanıldı" at line 65. in /var/www/html/flarum/vendor/symfony/translation/Loader/YamlFileLoader.php:50
Stack trace:
#0 /var/www/html/flarum/vendor/symfony/translation/Loader/FileLoader.php(36): Symfony\Component\Translation\Loader\YamlFileLoader->loadResource()
#1 /var/www/html/flarum/vendor/flarum/core/src/Locale/PrefixedYamlFileLoader.php(21): Symfony\Component\Translation\Loader\FileLoader->load()
#2 /var/www/html/flarum/vendor/symfony/translation/Translator.php(385): Flarum\Locale\PrefixedYamlFileLoader->load()
#3 /var/www/html/flarum/vendor/symfony/translation/Translator.php(277): Symfony\Component\Translation\Translator->doLoadCatalogue()
#4 /var/www/html/flarum/vendor/symfony/translation/Translator.php(314): Symfony\Component\Translation\Translator->initializeCatalogue()
#5 /var/www/html/flarum/vendor/symfony/translation/Translator.php(299): Symfony\Component\Translation\Translator->dumpCatalogue()
#6 /var/www/html/flarum/vendor/symfony/config/ConfigCacheFactory.php(46): Symfony\Component\Translation\Translator->Symfony\Component\Translation\{closure}()
#7 /var/www/html/flarum/vendor/symfony/translation/Translator.php(300): Symfony\Component\Config\ConfigCacheFactory->cache()
#8 /var/www/html/flarum/vendor/symfony/translation/Translator.php(265): Symfony\Component\Translation\Translator->initializeCacheCatalogue()
#9 /var/www/html/flarum/vendor/symfony/translation/Translator.php(241): Symfony\Component\Translation\Translator->loadCatalogue()
#10 /var/www/html/flarum/vendor/flarum/core/src/Locale/Translator.php(43): Symfony\Component\Translation\Translator->getCatalogue()
#11 /var/www/html/flarum/vendor/symfony/translation/Translator.php(198): Flarum\Locale\Translator->getCatalogue()
#12 /var/www/html/flarum/vendor/flarum/core/src/Api/Serializer/GroupSerializer.php(65): Symfony\Component\Translation\Translator->trans()
#13 /var/www/html/flarum/vendor/flarum/core/src/Api/Serializer/GroupSerializer.php(51): Flarum\Api\Serializer\GroupSerializer->translateGroupName()
#14 /var/www/html/flarum/vendor/flarum/core/src/Api/Serializer/AbstractSerializer.php(84): Flarum\Api\Serializer\GroupSerializer->getDefaultAttributes()
#15 /var/www/html/flarum/vendor/tobscure/json-api/src/Resource.php(169): Flarum\Api\Serializer\AbstractSerializer->getAttributes()
#16 /var/www/html/flarum/vendor/tobscure/json-api/src/Resource.php(75): Tobscure\JsonApi\Resource->getAttributes()
#17 /var/www/html/flarum/vendor/tobscure/json-api/src/Document.php(187): Tobscure\JsonApi\Resource->toArray()
#18 [internal function]: Tobscure\JsonApi\Document->Tobscure\JsonApi\{closure}()
#19 /var/www/html/flarum/vendor/tobscure/json-api/src/Document.php(186): array_map()
#20 /var/www/html/flarum/vendor/tobscure/json-api/src/Document.php(224): Tobscure\JsonApi\Document->toArray()
#21 /var/www/html/flarum/vendor/flarum/core/src/Api/JsonApiResponse.php(27): Tobscure\JsonApi\Document->jsonSerialize()
#22 /var/www/html/flarum/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(111): Flarum\Api\JsonApiResponse->__construct()
#23 /var/www/html/flarum/vendor/flarum/core/src/Api/Client.php(72): Flarum\Api\Controller\AbstractSerializeController->handle()
#24 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Frontend.php(72): Flarum\Api\Client->send()
#25 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Frontend.php(51): Flarum\Frontend\Frontend->getForumDocument()
#26 /var/www/html/flarum/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
#27 /var/www/html/flarum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Frontend\Controller->handle()
#28 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#29 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process()
#30 /var/www/html/flarum/vendor/flarum/core/src/Admin/Middleware/RequireAdministrateAbility.php(23): Laminas\Stratigility\Next->handle()
#31 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Admin\Middleware\RequireAdministrateAbility->process()
#32 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#33 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#34 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(37): Laminas\Stratigility\Next->handle()
#35 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#36 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#37 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#38 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle()
#39 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#40 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#41 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#42 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#43 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#44 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#45 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#46 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#47 /var/www/html/flarum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#48 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#49 /var/www/html/flarum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle()
#50 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#51 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#52 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#53 /var/www/html/flarum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#54 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#55 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#56 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#57 /var/www/html/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#58 /var/www/html/flarum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#59 /var/www/html/flarum/public/index.php(26): Flarum\Http\Server->listen()
#60 {main}  
```

**Comment by dsevillamartin** [comment]
That is an issue with the Turkish locale file in tolgaaaltas/flarum-ext-turkish

**Comment by ghost** [comment]
https://github.com/tolgaaaltas/flarum-ext-turkish/issues/19
